using ManiaAPI.ManiaPlanetAPI.Converters;
using System.Text.Json.Serialization;

namespace ManiaAPI.ManiaPlanetAPI;

public sealed record IngameTitle(string Uid,
                                 string Name,
                                 string Description,
                                 string Punchline,
                                 [property: JsonPropertyName("author_login")] string AuthorLogin,
                                 [property: JsonPropertyName("author_nickname")] string AuthorNickname,
                                 [property: JsonPropertyName("download_url")] string DownloadUrl,
                                 [property: JsonPropertyName("creation_date"), JsonConverter(typeof(DateTimeOffsetUnixConverter))] DateTimeOffset CreationDate,
                                 [property: JsonPropertyName("last_update"), JsonConverter(typeof(DateTimeOffsetUnixConverter))] DateTimeOffset LastUpdate,
                                 int Cost,
                                 int Registrations,
                                 [property: JsonPropertyName("players_last24h")] int PlayersLast24h,
                                 [property: JsonPropertyName("online_players")] int OnlinePlayers,
                                 [property: JsonPropertyName("facebook_url")] string? FacebookUrl,
                                 [property: JsonPropertyName("twitter_url")] string? TwitterUrl,
                                 [property: JsonPropertyName("youtube_url")] string? YoutubeUrl,
                                 [property: JsonPropertyName("forum_url")] string? ForumUrl,
                                 [property: JsonPropertyName("website_url")] string? WebsiteUrl,
                                 [property: JsonPropertyName("card_url")] string CardUrl,
                                 [property: JsonPropertyName("background_url")] string BackgroundUrl,
                                 [property: JsonPropertyName("logo_url")] string LogoUrl,
                                 [property: JsonPropertyName("is_solo")] bool IsSolo,
                                 [property: JsonPropertyName("is_multiplayer")] bool IsMultiplayer,
                                 [property: JsonPropertyName("is_environment")] bool IsEnvironment,
                                 [property: JsonPropertyName("is_trackmania")] bool IsTrackmania,
                                 [property: JsonPropertyName("is_shootmania")] bool IsShootmania,
                                 [property: JsonPropertyName("is_matchmaking")] bool IsMatchmaking,
                                 [property: JsonPropertyName("primary_color")] string PrimaryColor,
                                 [property: JsonPropertyName("title_maker_uid")] string TitleMakerUid,
                                 [property: JsonPropertyName("title_maker_name")] string TitleMakerName,
                                 [property: JsonPropertyName("title_page_url")] string TitlePageUrl,
                                 [property: JsonPropertyName("screenshot_url_0")] string ScreenshotUrl0,
                                 [property: JsonPropertyName("screenshot_url_1")] string ScreenshotUrl1,
                                 [property: JsonPropertyName("youtube_id_0")] string YoutubeId0,
                                 [property: JsonPropertyName("youtube_id_1")] string YoutubeId1,
                                 [property: JsonPropertyName("youtube_id_2")] string YoutubeId2);