using Microsoft.Extensions.Configuration;
using System.Threading.Tasks;
using Xunit;

namespace ManiaAPI.NadeoAPI.Tests.Integration;

public class NadeoLiveServicesTests
{
    [Fact]
    public async Task RequestManagement()
    {
        // Arrange
        var configuration = new ConfigurationBuilder()
            .AddUserSecrets<AutoGeneratedProgram>()
            .Build();

        var login = configuration.GetValue<string>("DedicatedServer:Login");
        var password = configuration.GetValue<string>("DedicatedServer:Password");

        var nadeoLiveServices = new NadeoLiveServices();
        
        // Act
        await nadeoLiveServices.AuthorizeAsync(login, password);

        var topLeaderboard = await nadeoLiveServices.GetTopLeaderboardAsync("2katsDjZmPOeQYE94jkbnSoJA64");

        // Assert
        Assert.IsType<TopLeaderboardCollection>(topLeaderboard);
    }
}
