using Microsoft.Extensions.Configuration;
using System;
using System.Threading.Tasks;
using Xunit;

namespace ManiaAPI.NadeoAPI.Tests.Integration;

public class NadeoClubServicesTests
{
    [Fact]
    public async Task RequestManagement()
    {
        // Arrange
        var configuration = new ConfigurationBuilder()
            .AddUserSecrets<AutoGeneratedProgram>()
            .Build();

        var login = configuration.GetValue<string>("DedicatedServer:Login") ?? throw new Exception("DedicatedServer:Login user secret is required");
        var password = configuration.GetValue<string>("DedicatedServer:Password") ?? throw new Exception("DedicatedServer:Password user secret is required");

        INadeoClubServices nadeoLiveServices = new NadeoClubServices();

        // Act
        await nadeoLiveServices.AuthorizeAsync(login, password, AuthorizationMethod.DedicatedServer);

        var result = await nadeoLiveServices.GetCurrentCupOfTheDayAsync();
    }
}
