using Microsoft.Extensions.Configuration;
using System;
using System.Threading;
using System.Threading.Tasks;
using Xunit;

namespace ManiaAPI.NadeoAPI.Tests.Integration;

public class NadeoLiveServicesTests
{
    [Fact]
    public async Task RequestManagement()
    {
        // Arrange
        var configuration = new ConfigurationBuilder()
            .AddUserSecrets<AutoGeneratedProgram>()
            .Build();

        var login = configuration.GetValue<string>("DedicatedServer:Login") ?? throw new Exception("DedicatedServer:Login user secret is required");
        var password = configuration.GetValue<string>("DedicatedServer:Password") ?? throw new Exception("DedicatedServer:Password user secret is required");

        INadeoLiveServices nadeoLiveServices = new NadeoLiveServices();
        
        // Act
        await nadeoLiveServices.AuthorizeAsync(login, password);

        var result = await nadeoLiveServices.GetPlayerSeasonRankingsAsync(Guid.Parse("6a43df20-cd1a-4b3b-87b9-a6835a9b416d"), "ee54d6c5-954c-49b9-bd82-b51f8175b3f7");
        // Assert
    }
}
