using Microsoft.Extensions.Configuration;
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Xunit;

namespace ManiaAPI.NadeoAPI.Tests.Integration;

public class NadeoMeetServicesTests
{
    [Fact]
    public async Task RequestManagement()
    {
        // Arrange
        var configuration = new ConfigurationBuilder()
            .AddUserSecrets<AutoGeneratedProgram>()
            .Build();

        var login = configuration.GetValue<string>("DedicatedServer:Login") ?? throw new Exception("DedicatedServer:Login user secret is required");
        var password = configuration.GetValue<string>("DedicatedServer:Password") ?? throw new Exception("DedicatedServer:Password user secret is required");

        var handler = new HttpClientHandler
        {
            AllowAutoRedirect = false // test redirects so the Authorization header is not reset
        };

        var http = new HttpClient(handler);
        http.DefaultRequestHeaders.UserAgent.ParseAdd("NadeoMeetServices Integration Test 1.0");

#pragma warning disable CA1859
        INadeoMeetServices nadeoMeetServices = new NadeoMeetServices(http);
#pragma warning restore CA1859

        // Act
        await nadeoMeetServices.AuthorizeAsync(login, password);

#pragma warning disable IDE0059
        var cotd = await nadeoMeetServices.GetCurrentCupOfTheDayAsync();
        var cotds = await nadeoMeetServices.GetCupsOfTheDayAsync(CupOfTheDayType.COTW);
#pragma warning restore IDE0059
    }
}
