namespace ManiaAPI.TMX;

public enum TrackOrder
{
    None,
    UploadedOldest,
    UploadedNewest,
    UpdatedLeastRecent,
    UpdatedMostRecent,
    AwardsLeast,
    AwardsMost,
    CommentsLeast,
    CommentsMost,
    ActivityLeastRecent,
    ActivityMostRecent,
    TrackNameAZ,
    TrackNameZA,
    AuthorNameAZ,
    AuthorNameZA,
    DifficultyEasiest,
    DifficultyHardest,
    DownloadsLeast,
    DownloadsMost,
    ReplayScoreLeast,
    ReplayScoreMost,
    AwardsThisWeekLeast,
    AwardsThisWeekMost,
    AwardsThisMonthLeast,
    AwardsThisMonthMost,
    AwardedLeastRecent,
    AwardedMostRecent,
    WorldRecordSetLeastRecent,
    WorldRecordSetMostRecent,
    UserRecordSetLeastRecent,
    UserRecordSetMostRecent,
}
