using System.Collections.Immutable;
using System.Text.Json.Serialization;

namespace ManiaAPI.NadeoAPI;

[JsonSerializable(typeof(ImmutableList<Account>))]
[JsonSerializable(typeof(AuthorizationBody))]
[JsonSerializable(typeof(AuthorizationResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(JwtPayloadNadeoAPI))]
[JsonSerializable(typeof(MapInfoLiveCollection))]
[JsonSerializable(typeof(ImmutableList<MapRecord>))]
[JsonSerializable(typeof(MedalRecordCollection))]
[JsonSerializable(typeof(ImmutableList<ManiapubCollection>))]
[JsonSerializable(typeof(TopLeaderboardCollection))]
[JsonSerializable(typeof(TrackOfTheDayCollection))]
[JsonSerializable(typeof(TrackOfTheDayInfo))]
[JsonSerializable(typeof(CampaignCollection))]
[JsonSerializable(typeof(SeasonPlayerRankingCollection))]
[JsonSerializable(typeof(ImmutableList<PlayerZone>))]
[JsonSerializable(typeof(Dictionary<string, ApiRoute>))]
[JsonSerializable(typeof(ImmutableList<Zone>))]
[JsonSerializable(typeof(ImmutableList<PlayerClubTag>))]
[JsonSerializable(typeof(MapInfoCollection))]
[JsonSerializable(typeof(CupOfTheDay))]
[JsonSerializable(typeof(Competition))]
[JsonSerializable(typeof(Challenge))]
[JsonSerializable(typeof(DailyChannelJoin))]
[JsonSerializable(typeof(ClubMemberCollection))]
[JsonSerializable(typeof(ClubActivityCollection))]
[JsonSerializable(typeof(ClubCollection))]
[JsonSerializable(typeof(ClubCampaignCollection))]
[JsonSerializable(typeof(ClubCompetitionCollection))]
[JsonSerializable(typeof(ClubMapReviewRoomCollection))]
[JsonSerializable(typeof(ClubRoomCollection))]
[JsonSerializable(typeof(ClubBucketCollection))]
[JsonSerializable(typeof(ClubPlayerInfo))]
[JsonSerializable(typeof(ClubActivityEdition))]
[JsonSerializable(typeof(ClubCampaignEdition))]
[JsonSerializable(typeof(ImmutableList<WebIdentity>))]
[JsonSerializable(typeof(SkinInfo))]
[JsonSerializable(typeof(ClubFolder))]
[JsonSerializable(typeof(MapGroupIdCollection))]
[JsonSerializable(typeof(ImmutableList<Position>))]
[JsonSerializable(typeof(CupOfTheDayCollection))]
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, 
    PropertyNameCaseInsensitive = true, 
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
internal sealed partial class NadeoAPIJsonContext : JsonSerializerContext;
